// Code generated by goctl. DO NOT EDIT.
package Requests

type ArticlesIndexRequest struct {
	Keywords string `i:"keywords"`
	PerPage  int64  `i:"perPage" rule:"required" msg:"PerPage 必填"`
	Page     int64  `i:"page" rule:"required" msg:"Page 必填"`
	OrderBy  string `i:"orderBy" default:"id"`
	OrderDir string `i:"orderDir" default:"desc"`
}

type ArticlesStoreRequest struct {
	Title   string `i:"title" rule:"required" msg:"Title 必填"`
	Content string `i:"content" rule:"required" msg:"Content 必填"`
}
type ArticlesIdRequest struct {
	Id int64 `i:"id" rule:"required" msg:"id 必填"`
}
type ArticlesIdsRequest struct {
	Ids string `i:"ids" rule:"required" msg:"ids 必填"`
}
type ArticlesUpdateRequest struct {
	Id      int64  `i:"id" rule:"required" msg:"id 必填"`
	Title   string `i:"title" rule:"required" msg:"Title 必填"`
	Content string `i:"content" rule:"required" msg:"Content 必填"`
}
type ArticleItems struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
