// Code generated by goctl. DO NOT EDIT.

package Models

import (
	"time"
)

type Articles struct {
	Id        int64     `db:"id"`
	Title     string    `db:"title"`
	Content   string    `db:"content"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
